apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2021-09-11T17:04:14Z"
  generation: 4
  labels:
    app: pokedex
  name: pokedex
  namespace: pokedex
  resourceVersion: "3401"
  uid: d207561f-8e8b-4503-afef-b39286354b25
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pokedex
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pokedex
    spec:
      containers:
      - image: pokedex
        imagePullPolicy: Never
        name: pokedex
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-09-11T17:04:14Z"
    lastUpdateTime: "2021-09-11T17:05:20Z"
    message: ReplicaSet "pokedex-756df57897" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-09-11T17:38:45Z"
    lastUpdateTime: "2021-09-11T17:38:45Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
