apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pokedex
  name: pokedex
  namespace: pokedex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokedex
  template:
    metadata:
      labels:
        app: pokedex
    spec:
      containers:
      - image: pokedex
        imagePullPolicy: Never
        name: pokedex
