apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2021-09-11T16:46:24Z"
  labels:
    kubernetes.io/metadata.name: pokedex
  name: pokedex
  resourceVersion: "876"
  uid: 6566b6dd-e7d1-4294-b9b8-5b4322b9e331
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
