apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-09-11T17:07:22Z"
  labels:
    app: pokedex
  name: pokedex
  namespace: pokedex
  resourceVersion: "1892"
  uid: 68098d8b-882b-4649-a95c-41772727f8a2
spec:
  clusterIP: 10.109.52.56
  clusterIPs:
  - 10.109.52.56
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31691
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: pokedex
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
