apiVersion: v1
kind: Service
metadata:
  labels:
    app: pokedex
  name: pokedex
  namespace: pokedex
spec:
  ports:
  - nodePort: 30000
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: pokedex
  type: NodePort
